### ISSUE TITLE
Kanboard needs extra parameter for plugins to work

### ISSUE THREAD

**Issue by frakman1** [ArieDed/unraid-template#1]
I have found that I needed to add a volume mapping for `config.php` in order to get plugins to install from the plugins tab.

![image](https://user-images.githubusercontent.com/5826484/106370745-1ad76780-632b-11eb-98d9-f8ecfa3db276.png)

Here are the contents of `/mnt/user/appdata/mykanboard/config.php` for reference:

```php
<?php

defined('ENABLE_URL_REWRITE') or define('ENABLE_URL_REWRITE', true);
defined('LOG_DRIVER') or define('LOG_DRIVER', 'system');
define('PLUGIN_INSTALLER',true); 
```

Perhaps you can add that to your template.

**Comment by ArieDed** [comment]
There is already a custom config file at `/mnt/user/appdata/kanboard/data/config.php` where you can customize some settings, see [this link](https://docs.kanboard.org/en/latest/admin_guide/config_file.html). I'm not at home right now, but I can check tomorrow if this doesn't work for you.
